# Manual workflow to deploy to Firebase Hosting
name: Manual Firebase Deploy

on:
  workflow_dispatch: # This allows manual triggering from the GitHub Actions tab

jobs:
  deploy_static_app: # Renamed job for clarity
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # This action deploys your project to Firebase Hosting.
      # It expects your 'firebase.json' to correctly point to your public directory.
      # If your 'index.html' is at the root of your repository,
      # ensure your 'firebase.json' has:
      # {
      #   "hosting": {
      #     "public": "."
      #   }
      # }
      # If your files are in a folder (e.g., 'public'), then use:
      # {
      #   "hosting": {
      #     "public": "public"
      #   }
      # }
      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_GYM_CHECK_IN_D1BF5 }}
          channelId: live
          projectId: gym-check-in-d1bf5

